### ISSUE TITLE
About h1

### ISSUE THREAD

**Issue by fiatjaf** [mblode/marx#11]
See **Headings And Accessibility** on [The Importance Of HTML5 Sectioning Elements](http://www.smashingmagazine.com/2013/01/18/the-importance-of-sections/).

Ignoring the discussion about our need to use only `h1` (yes, we should be using only `h1`), there's something on this pure semantic thing and the importance of sectioning elements that Marx is overlooking: browsers are already styling headers differently according to the section they belong to.

Marx, however, forces all headers, independent of their section, to be of the same size.

**Comment by samwilson** [comment]
(Do you mean "use only *one* h1"?)

Headings currently *do* decrease in size as they go down in importance. Not by a huge amount, but it's quite noticible in many situations.

**Comment by fiatjaf** [comment]
no, I meant use _only h1_, not h2 or h3 or any h.

**Comment by samwilson** [comment]
ah right, that makes sense: because the hierarchy is provided by nesting `<section>` elements, is that it? It would be possible to style it so that one could do both (either nest sections, or use h1, h2, h3, ...).

**Comment by fiatjaf** [comment]
Well, probably with something like `section h1`, `header h1`, `section header h1`, `article h1`. I don't know. We should see how Chrome styles it in its default stylesheet.

**Comment by ricklancee** [comment]
> yes, we should be using only h1

No, we shouldn't. See the spec: 

> There are currently no known implementations of the outline algorithm in graphical browsers or assistive technology user agents, although the algorithm is implemented in other software such as conformance checkers. **Therefore the outline algorithm cannot be relied upon to convey document structure to users.** Authors are advised to use heading rank (h1-h6) to convey document structure.  
http://www.w3.org/TR/html5/sections.html#outlines

It is currently discouraged to use only h1. Stick to one h1, then use h2-h6s
