### ISSUE TITLE
Marx.css or marx.min.css?

### ISSUE THREAD

**Issue by megageektutorials** [mblode/marx#16]
I have opened both files in my editor and while I haven't gone line by line, they both looks about the same and almost have the same number of lines. 

Also, I kind of have another topic but didn't want to spam the issues with my questions. In the marx demo seen here [http://codepen.io/mblode/details/QNaKMe](http://codepen.io/mblode/details/QNaKMe) it says the article tag is 60%, the aside 40%, and section 100%. In the CSS file (both marx and marx.min) the article selector is set to "width: 100%" and so is Aside. Am I not understanding something fundamental about this?

I'm referencing it correctly in my html. It worked fine pulling it from here as well.
`<link rel="stylesheet" href="https://cdn.rawgit.com/mblode/marx/master/css/marx.min.css">`

[http://puu.sh/pSUsH/945f15794c.png](http://puu.sh/pSUsH/945f15794c.png)

**Comment by indrora** [comment]
It looks like at some point, aside and such were given full widths (instead of sidebar-like abilities)

**Comment by megageektutorials** [comment]
so what's the point of article and aside? I guess the demo is not up to date anymore.
