### ISSUE TITLE
Seems that the tag for PR #18 was not included in the merge

### ISSUE THREAD

**Issue by eriknstr** [mblode/marx#19]
Hello, thanks for merging PR #18. I also had a tag included, produced with "git tag -m v2.0.5 v2.0.5", but I guess maybe tags are not included by GitHub in Pull Requests? Please tag the commit manually and push the tag to your repo.

**Comment by mblode** [comment]
Ok i have now published a release with the tag of 2.0.7 (Because of some trial and error)
