### ISSUE TITLE
Demo Page Checkbox for attributes faulty

### ISSUE THREAD

**Issue by inoas** [mblode/marx#27]
### Problem

When you click on the label of checkbox 2 on the demo page, checkbox 1 will get toggled (tested on Firefox).

### How things are

```html
<h3>Checkbox Buttons</h3>
<label for=checkbox>Checkbox 1:</label> <input type=checkbox name=checkbox id=checkbox /><br>
<label for=checkbox>Checkbox 2:</label> <input type=checkbox name=checkbox id=checkbox />
```

### How they should be

```html
<h3>Checkbox Buttons</h3>
<label for=checkbox1>Checkbox 1:</label> <input type=checkbox1 name=checkbox1 id=checkbox1 /><br>
<label for=checkbox2>Checkbox 2:</label> <input type=checkbox2 name=checkbox2 id=checkbox2 />
```

@mblode can you fix it? @ https://codepen.io/mblode/details/JdYbJj

**Comment by mblode** [comment]
Good spot! I also added "" around all the attributes.

**Comment by inoas** [comment]
You can also make it xhtml5-polyglot (including always specifying a value for every attribute) as that IMHO/AFAIK only has benefits, but no need. As long as the demo runs everything is fine.

Thanks for fixing it!
