### ISSUE TITLE
Update Codepen, NPM Repo, Bower Repo

### ISSUE THREAD

**Issue by inoas** [mblode/marx#35]
* Update npm to 3.0.1 https://www.npmjs.com/package/marx-css
* Update Codepen to use use https://raw.githubusercontent.com/mblode/marx/master/css/marx.min.css
* Update the size on Codepen demo page It is now 11.6 KiB / 3.7 KiB (Gzip) - <img width="606" alt="screen shot 2018-03-12 at 11 10 25" src="https://user-images.githubusercontent.com/20972207/37277801-1dadbaf2-25e6-11e8-8347-111994f1706b.png">
* Update bower repo?

**Comment by mblode** [comment]
Thanks for being so on top of these things! Everything has been super hectic for the past few days but I'm free this entire morning to tie up all the loose ends and get this released properly 😄

**Comment by inoas** [comment]
I'd have taken it up myself but I cannot (no privileges). I am ok with that. I know that F(L)OSS can be non-rewarding. I thank you for doing marx.

It [almost made it way into phoenix framework](https://github.com/phoenixframework/phoenix/pull/2785#issuecomment-372018670) but then they chose [Miligram](https://milligram.io/) which has a lot of non-class styles but sadly some with classes (and an annoying default dependency to Roboto and broken Kerning).

Once flexbox gets a little bit more support and [grid](https://caniuse.com/css-grid) a ton more I hope that we can say good bye to those heavy div-soupy frameworks.

However for things like grouping form labels and stuff we still miss css features like this: https://gist.github.com/inoas/8c66373a9f41e65fab988cb88feb7960
See https://github.com/w3c/csswg-drafts/issues/2406

Best to you on the other side of the globe :)

**Comment by inoas** [comment]
I'd have taken it up myself but I cannot (no privileges). I am ok with that. I know that F(L)OSS can be non-rewarding. I thank you for doing marx.

It [almost made it way into phoenix framework](https://github.com/phoenixframework/phoenix/pull/2785#issuecomment-372018670) but then they chose [Miligram](https://milligram.io/) which has a lot of non-class styles but sadly some with classes (and an annoying default dependency to Roboto and broken Kerning).

Once flexbox gets a little bit more support and [grid](https://caniuse.com/css-grid) a ton more I hope that we can say good bye to those heavy div-soupy frameworks.

However for things like grouping form labels and stuff we still miss css features like this: https://gist.github.com/inoas/8c66373a9f41e65fab988cb88feb7960
See `https://github.com/w3c/csswg-drafts/issues/2406`

Best to you on the other side of the globe :)
