### ISSUE TITLE
When installing via NPM, sanatize.css dependency is missing

### ISSUE THREAD

**Issue by kevinriemens** [mblode/marx#36]
Perhaps put it in as a peer dependency?
Out of the box, it breaks an angular 6 apllication build because of the missing depedency.

It's an easy fix, but perhaps a good addition to the project, to add it as a peer depedency in the package.json.

**Comment by inoas** [comment]
I ran npm install --save-dev sanitize.css@5.0.0

And in marx.scss, I had to change:

```css
@import '../node_modules/sanitize.css/sanitize';
```

to:

```css
@import '../../sanitize.css/sanitize';
```
