### ISSUE TITLE
Dropdown does not show indicator in Firefox

### ISSUE THREAD

**Issue by troxler** [mblode/marx#38]
The dropdown styling is off in Firefox (and probably other non-WebKit/non-Blink browsers). It does not show the dropdown indicator as can be seen in the following screenshot:

![screen shot 2019-01-02 at 22 21 42](https://user-images.githubusercontent.com/2767948/50613249-3c13c280-0edd-11e9-87a6-6696c929691a.png)

There is probably no need to have `-webkit-appearance: menulist-button;` on a `select` element at all. And if there is, it probably should be `menulist` instead of `menulist-button`.

**Comment by mblode** [comment]
Thank you for letting me know! I've fixed this in version 3.0.5 😄

**Comment by troxler** [comment]
Thank you :) Marx is now also listed in https://github.com/troxler/awesome-css-frameworks
