### ISSUE TITLE
$link-hover-color is not used

### ISSUE THREAD

**Issue by Schnouki** [mblode/marx#55]
**Describe the bug**
Variable `$link-hover-color` is defined but never used. Instead, the default color for `a:focus` and `a:hover` is `darken($primary, 10%`), which doesn't depend on `$link-color`, and isn't even the default value of `$link-hover-color`.

**Expected behavior**
This variable should be used for `a:hover` and `a:focus`.

**Comment by mblode** [comment]
Fixed in v4.0.1
